In [18]:
from tools.utils import *
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import torch
import spacy

# Prepare data for annotation

In [19]:
# prepare the spacy model and pipeline
nlp = spacy.load("en_core_web_sm")
nlp.disable_pipes("tagger", "parser", "attribute_ruler", "lemmatizer")
nlp.add_pipe('sentencizer')

In [50]:
processed_data_dir = Path('processed_data/multigenre')

In [51]:
embeddings = np.loadtxt(processed_data_dir / 'embedding.tsv')
metadata = pd.read_csv(processed_data_dir / 'metadata.tsv',sep='\t')
print(len(embeddings), len(metadata))

149261 149261

In [86]:
metadata.columns

Index(['file_name', 'platform', 'genre', 'tag', 'sentence'], dtype='object')

# Clause classification

In [141]:
clause_type = 'opt-out' #'arbitration' | 'opt-out' | 'class_waiver' | 'anti-scraping'
examples_df = pd.read_excel(f'annotations/seed_examples/{clause_type}_clauses.xlsx', sheet_name='Sheet1')

In [142]:
examples_df['processed_text'] = examples_df['Examples'].apply(lambda x: 'clustering: ' + replace_named_entities(nlp(x)))

In [143]:
examples_df['processed_text']

0     clustering: if you are a new grindr user , you...
1     clustering: you may opt out of this agreement ...
2     clustering: you can opt out of this provision ...
3     clustering: notwithstanding any provision in t...
4     clustering: you may decline to resolve dispute...
5     clustering: you will retain the right to opt o...
6     clustering: you have the right within [mask] (...
7     clustering: opt - out . you may opt out of [ma...
8     clustering: if you do not want to arbitrate di...
9     clustering: you have the right to opt - out an...
10    clustering: you may opt out of arbitration wit...
11    clustering: you can choose to reject this agre...
12    clustering: if you do not wish to be bound by ...
13    clustering: you can choose to reject this agre...
14    clustering: you may opt out of this agreement ...
Name: processed_text, dtype: object

In [144]:
# next line is to check if MPS is available
device = 'mps' if torch.backends.mps.is_available() else 'cpu'
# comment next line if you are want to run code on a GPU
#device = 'cuda' if torch.cuda.is_available() else device

# load the nomic embed model
model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True) # trust_remote_code is needed to use the encode method
# send the model to the device
#model.to(device)
#print(device)

/Users/kasparbeelen/anaconda3/envs/tou/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
<All keys matched successfully>

In [145]:
target_embeddings = model.encode(examples_df['processed_text'].tolist())

In [146]:
average_embedding = target_embeddings.mean(axis=0)

In [147]:
similarity_scores = cosine_similarity(embeddings, [average_embedding])
top_n_position = np.argpartition(similarity_scores.reshape(-1), -500)[-500:][::-1]
out_csv = pd.DataFrame(metadata.iloc[top_n_position].sentence.unique())
out_csv.columns = ['sentence']
out_csv['label'] = 0
#out_csv['similarity'] = similarity_scores[top_n_position]
out_csv.to_csv(f'annotations/similar_examples/{clause_type}_most_similar_to_average.csv')

In [148]:
similarity_scores = cosine_similarity(embeddings, target_embeddings)
similarity_scores = similarity_scores.max(axis=1)
top_n_position = np.argpartition(similarity_scores, -500)[-500:][::-1]
out_csv = pd.DataFrame(metadata.iloc[top_n_position].sentence.unique())
out_csv.columns = ['sentence']
out_csv['label'] = 0
#out_csv['similarity'] = similarity_scores[top_n_position]
out_csv.to_csv(f'annotations/similar_examples/{clause_type}_most_similar_to_individual.csv')

## Pre-annotate selected examples with ChatGPT

In [149]:
# prepare examples for annotation
df1 = pd.read_csv(f'annotations/similar_examples/{clause_type}_most_similar_to_individual.csv', index_col=0)
df2 = pd.read_csv(f'annotations/similar_examples/{clause_type}_most_similar_to_average.csv', index_col=0)
print(len(df1) + len(df2))
df = pd.concat([df1, df2], axis=0).drop_duplicates(subset='sentence').sample(100).reset_index(drop=True)
print(df.shape)

743
(100, 2)

In [150]:
df

                                             sentence  label
0   this opt - out notice must be sent within [mas...      0
1   the opt out notice must clearly state that you...      0
2   the opt - out notice must be postmarked [mask]...      0
3   if you opt out of the provisions requiring arb...      0
4   to start an arbitration , submit the form avai...      0
..                                                ...    ...
95   you may opt out of this agreement to arbitrate .      0
96  if the [mask] is unavailable or unwilling to d...      0
97  before you commence arbitration of a [mask] , ...      0
98  by accepting this arbitration provision , you ...      0
99  you may reject [mask] [mask] [mask] and opt ou...      0

[100 rows x 2 columns]

In [151]:
definitions = {
    'class waiver' : """A class action waiver is a provision found in some contracts which prohibits a party from filing a class action legal proceeding against the other party, or both parties waiving the right to file class actions against each other. Most class action waiver clauses include this wording or a variation of it: You and we agree that any dispute filed against each other must be on an individual basis and not as a class or collective action.""",
    'opt-out' : """a clause that permits signatories to a contract to opt out of particular provisions, or to terminate the contract early""",
    'arbitration': """In contract law, an arbitration clause is a clause in a contract that requires the parties to resolve their disputes through an arbitration process. Although such a clause may or may not specify that arbitration occur within a specific jurisdiction, it always binds the parties to a type of resolution outside the courts, and is therefore considered a kind of forum selection clause."""
}

In [152]:
# prepare prompts for annotation
sentences = df.sentence.to_list()
definition = definitions[clause_type]
prompts =["""
          
You are a helpful AI that classifies sentences from legal as being a {0} clause or not. 

We first provide a definition followed by five examples of {0} clauses. 
          
DEFINITON: 
The defintion of of {0} clause is: {3}

EXAMPLES:          
Below are five examples of {0} clauses.\n\n{1}
          
QUESTION:
Is the following sentence a {0} clause? Please reply only 'yes' or 'no':
{2}
""".format(
     clause_type,examples_df['Examples'].sample(5).str.cat(sep='\n'),s, definition)  for s in sentences]
print(len(prompts),prompts[0])

100

You are a helpful AI that classifies sentences from legal as being a opt-out clause or not.

We first provide a definition followed by five examples of opt-out clauses.

DEFINITON:
The defintion of of opt-out clause is: a clause that permits signatories to a contract to opt out of particular provisions, or to terminate the contract early

EXAMPLES:
Below are five examples of opt-out clauses.

You can choose to reject this Agreement to Arbitrate by mailing us a written opt-out notice. For new [mask] users, the Opt-Out Notice must be postmarked no later than 30 Days after the date you accept the User Agreement for the first time
IF YOU ARE A NEW GRINDR USER, YOU CAN CHOOSE TO REJECT THE AGREEMENT TO ARBITRATE PROVISION (“OPT-OUT”) BY EMAILING US AN OPT-OUT NOTICE TO ARBITRATIONOPTOUT@GRINDR.COM (“OPT-OUT NOTICE”). THE OPT-OUT NOTICE MUST BE RECEIVED WITHIN THIRTY-ONE (31) DAYS AFTER THE DATE YOU ACCEPT THE TERMS OF THIS AGREEMENT FOR THE FIRST TIME. IF YOU ARE NOT A NEW GRINDR USER, YOU HAVE UNTIL THIRTY-ONE (31) DAYS AFTER THE POSTING OF THE NEW TERMS TO SUBMIT AN ARBITRATION OPT-OUT NOTICE.
You may opt out of this agreement to arbitrate. If you do so, neither we nor you can require the other to participate in an arbitration proceeding. To opt out, you must notify us in writing postmarked within 30 days of the later of: (i) the date that you first accepted our Terms; and (ii) the date you became subject to this arbitration provision.
If you do not want to arbitrate disputes with TikTok and you are an individual, you may opt out of this arbitration agreement by sending an email to legal@tiktok.com within thirty (30) days of the first of the date you access or use the Services
You have the right within thirty (30) days of first accepting these Terms to decline this agreement to arbitrate. To do so, you must send written notice with your name, address, username, email address or phone number that you use for your Service account, identify the Service(s) you use, and clearly state that you want to opt out of the Terms of Service arbitration agreement.

QUESTION:
Is the following sentence a opt-out clause? Please reply only 'yes' or 'no':
this opt - out notice must be sent within [mask] ( [mask] [mask] [mask] of when we notify users of the change and include : ( [mask] ) your name , address , email address associated with your [mask] account , phone number , and [mask] username .

In [153]:
# sentences = df.sentence.to_list()
# syntethic_prompts =["""Below are ten examples of {0} clauses.\n\n{1}\n\nGenerate a new sentence similar but not identical to these examples and has the same function as {0} clause.
#  """.format(
#      clause_type,examples_df['Examples'].sample(10).str.cat(sep='\n'))  for _ in range(100)]
# print(len(syntethic_prompts),syntethic_prompts[0])

In [154]:
# Set up OpenAI API credentials
from openai import OpenAI
client = OpenAI()


def generate_response(prompt,model='gpt-4o-mini', max_tokens=100,temperature=.0):
    # Generate a response using OpenAI ChatGPT
    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_tokens,
        temperature=temperature,
        n=1,
        stop=None,
        timeout=10
    )

    # Extract the generated response from the API response
    #generated_response = response.choices[0].text.strip()

    return response.choices[0].message.content

In [155]:
responses = [(sentences[i],generate_response(p,model='gpt-4o',max_tokens=2)) for i, p in tqdm(enumerate(prompts))]
responses_df = pd.DataFrame(responses, columns=['text','response'])

100it [00:51,  1.94it/s]

In [156]:
# responses_df['synthetic'] = 0

In [157]:
responses_df.value_counts('response')

response
No     30
yes    25
no     24
Yes    21
Name: count, dtype: int64

In [158]:
responses_df.response.unique()

array(['Yes', 'No', 'no', 'yes'], dtype=object)

In [159]:
# syntethic_data = [generate_response(p,max_tokens=200,temperature=.3) for i, p in tqdm(enumerate(syntethic_prompts))]

In [160]:
# syntethic_data_df = pd.DataFrame(syntethic_data, columns=['text'])
# syntethic_data_df['text'] = syntethic_data_df['text'].str.lower()
# syntethic_data_df['labels'] = 1
# syntethic_data_df['synthetic'] = 1
# syntethic_data_df.iloc[1]

In [161]:
responses_df.replace({'response': {'Yes.': 1,'Yes': 1,'yes.': 1,'yes': 1, 'No': 0,'No.': 0,'no': 0,'no.': 0}}, inplace=True)
responses_df.rename(columns={'response': 'labels'}, inplace=True)

In [162]:
responses_df.labels.unique()

array([1, 0])

In [163]:
responses_df.labels.value_counts()

labels
0    54
1    46
Name: count, dtype: int64

In [164]:
#annotations_gpt = pd.concat([responses_df, syntethic_data_df], axis=0)

In [165]:
responses_df.to_csv(f'annotations/gpt4_annotations/{clause_type}_annotations_gpt4.csv')
responses_df.shape

(100, 2)

# Evaluate Annotations

In [210]:
clause_type = 'opt-out' #'arbitration' | 'opt-out' | 'class_waiver' 
annotator = '_TS'
annotations_df = pd.read_excel(f'annotations/manual/{clause_type}_annotations_gpt4{annotator}.xlsx',
                               sheet_name=f'{clause_type}_annotations_gpt4', index_col=0)
predictions_df = pd.read_csv(f'annotations/gpt4_annotations/{clause_type}_annotations_gpt4.csv', index_col=0)

In [211]:
predictions_df = predictions_df[~annotations_df.labels.isnull()]
annotations_df = annotations_df[~annotations_df.labels.isnull()]
annotations_df.shape, predictions_df.shape

((98, 3), (98, 2))

In [212]:
annotations_df.labels = annotations_df.labels.astype(int)
predictions_df.labels = predictions_df.labels.astype(int)
annotations_df.replace({'labels': {2: 1}}, inplace=True)

In [214]:

print(classification_report(annotations_df.labels, predictions_df.labels))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        54
           1       0.95      0.95      0.95        44

    accuracy                           0.96        98
   macro avg       0.96      0.96      0.96        98
weighted avg       0.96      0.96      0.96        98

# Synthetic data

In [288]:
from sklearn.metrics import classification_report, accuracy_score, f1_score
import re

In [289]:
clause_type = 'arbitration' #'arbitration' | 'opt-out' | 'class_waiver' 
annotator = '_TS'
annotations_df = pd.read_excel(f'annotations/manual/{clause_type}_annotations_gpt4{annotator}.xlsx',
                               sheet_name=f'{clause_type}_annotations_gpt4', index_col=0)

annotations_df = annotations_df[~annotations_df.labels.isnull()]
annotations_df.labels = annotations_df.labels.astype(int)
annotations_df.replace({'labels': {2: 1}}, inplace=True)
annotations_df.labels.value_counts(normalize=True)

labels
1    0.833333
0    0.166667
Name: proportion, dtype: float64

In [290]:
annotations_df.drop_duplicates(subset='text', inplace=True)
annotations_df.shape

(96, 3)

In [291]:
import re

def replace_mask_with_company(text):
    return re.sub(r'(\[mask\]\s)+', r'[company] ', text)

annotations_df['text'] = annotations_df.text.apply(replace_mask_with_company)

In [292]:

train,test = train_test_split(annotations_df, test_size=0.75, random_state=42)

In [293]:
train.labels.value_counts()

labels
1    20
0     4
Name: count, dtype: int64

In [294]:
definitions = {
    'class waiver' : """A class action waiver is a provision found in some contracts which prohibits a party from filing a class action legal proceeding against the other party, or both parties waiving the right to file class actions against each other. Most class action waiver clauses include this wording or a variation of it: You and we agree that any dispute filed against each other must be on an individual basis and not as a class or collective action.""",
    'opt-out' : """a clause that permits signatories to a contract to opt out of particular provisions, or to terminate the contract early""",
    'arbitration': """In contract law, an arbitration clause is a clause in a contract that requires the parties to resolve their disputes through an arbitration process. Although such a clause may or may not specify that arbitration occur within a specific jurisdiction, it always binds the parties to a type of resolution outside the courts, and is therefore considered a kind of forum selection clause."""
}

In [298]:
num_examples = 100

In [301]:
# prepare prompts for generating synthetic data
# here we focus on positive examples

definition = definitions[clause_type]
prompts_positive =["""
          
You are a helpful AI that creates synthetic data by generating new examples a {0} clause. We replaced the name of the company with a "[company]" token and lowercased all characters.

We first provide a definition followed by five examples of {0} clauses. You need to generate a new sentence similar but NOT identical to these examples and has the same legal function as {0} clause. 
          
DEFINITON: 
The defintion of of {0} clause is: {2}

EXAMPLES:          
Below are three examples of {0} clauses.\n\n{1}
          
NEW EXAMPLE:
""".format(
     clause_type,train[train.labels==1].text.sample(3).str.cat(sep='\n'),definition)  for _ in range(num_examples)]
print(len(prompts_positive),prompts_positive[0])

100

You are a helpful AI that creates synthetic data by generating new examples a arbitration clause. We replaced the name of the company with a "[company]" token and lowercased all characters.

We first provide a definition followed by five examples of arbitration clauses. You need to generate a new sentence similar but NOT identical to these examples and has the same legal function as arbitration clause.

DEFINITON:
The defintion of of arbitration clause is: In contract law, an arbitration clause is a clause in a contract that requires the parties to resolve their disputes through an arbitration process. Although such a clause may or may not specify that arbitration occur within a specific jurisdiction, it always binds the parties to a type of resolution outside the courts, and is therefore considered a kind of forum selection clause.

EXAMPLES:
Below are three examples of arbitration clauses.

you and [company] agree that any past , pending , or future dispute , claim or controversy arising out of or relating to your access to or use of [company] ( including services ) or to these terms of use ( including without limitation any dispute concerning the breach , enforcement , construction , validity , interpretation , enforceability , or arbitrability of [company] ) ( a " [company] " ) , shall be determined by arbitration , except that you and [company] are not required to arbitrate any [company] in which either party seeks equitable and other relief for the alleged unlawful use of copyrights , trademarks , trade names , logos , trade secrets , or patents .
by agreeing to this agreement , you also agree to   [company]   and acknowledge that you have read [company] , which includes using arbitration to resolve claims related to [company] .
dispute resolution you and [company] agree that any dispute , claim or controversy that has arisen , or may arise , between you and [company] out of or relating to these terms ( including previous versions of these terms ) or the breach , termination , enforcement , interpretation , or validity thereof , your use of or access to the [company] , the actions of [company] or its agents , or any products or services sold , offered , or purchased through the service ( collectively , [company] ) shall be settled by final and binding arbitration , except that each party retains the right to bring an individual action in small claims court and the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement , misappropriation , or violation of a partys copyrights , trademarks , trade secrets , patents , or other intellectual property rights .

NEW EXAMPLE:

In [302]:
# prepare prompts for generating synthetic data
# here we focus on positive examples

definition = definitions[clause_type]
prompts_negative = [""" You are a helpful AI that creates synthetic data by generating new examples that look like a {0} clause but have a different meaning. 
We replaced the name of the company with a "[company]" token and lowercased all characters.

We first provide three examples of sentences that resemble {0} clauses BUT have a different meaning. 
You need to generate a new sentence similar but not identical to these examples. They are NOT allowed to be a {0}. 
          
DEFINITON: 
The defintion of of {0} clause is: {2}

EXAMPLES:          
Below are five examples of {0} clauses.\n\n{1}
          
NEW EXAMPLE:
""".format(
     clause_type, train[train.labels==0].text.sample(3).str.cat(sep='\n'), definition
          )  for _ in range(num_examples)]
print(len(prompts_negative),prompts_negative[0])

100  You are a helpful AI that creates synthetic data by generating new examples that look like a arbitration clause but have a different meaning.
We replaced the name of the company with a "[company]" token and lowercased all characters.

We first provide three examples of sentences that resemble arbitration clauses BUT have a different meaning.
You need to generate a new sentence similar but not identical to these examples. They are NOT allowed to be a arbitration.

DEFINITON:
The defintion of of arbitration clause is: In contract law, an arbitration clause is a clause in a contract that requires the parties to resolve their disputes through an arbitration process. Although such a clause may or may not specify that arbitration occur within a specific jurisdiction, it always binds the parties to a type of resolution outside the courts, and is therefore considered a kind of forum selection clause.

EXAMPLES:
Below are five examples of arbitration clauses.

the laws of [company] , [company] , regardless of conflict of laws principles , govern all matters arising out of or relating to this agreement , including its interpretation , construction , performance , and enforcement , except that the [company] governs provisions relating to arbitration .
[company] that are not subject to [company] or that are severed from any arbitration may only be litigated in the federal or state courts of [company] , [company] ; and the parties consent to personal and exclusive jurisdiction in these courts , except as otherwise provided by the [company] .
if the above arbitration terms are not enforceable on any dispute , both parties agree that such dispute shall be brought in a court in [company] .

NEW EXAMPLE:

In [303]:
responses_postivite = [(p,generate_response(p,model='gpt-4o',max_tokens=100, temperature=0.5)) for i, p in tqdm(enumerate(prompts_positive))]
responses_df_postive = pd.DataFrame(responses_postivite, columns=['text','response'])

0it [00:00, ?it/s]

In [305]:
responses_df_postive['labels'] = 1

In [306]:
responses_negative = [(p,generate_response(p,model='gpt-4o',max_tokens=100, temperature=0.5)) for i, p in tqdm(enumerate(prompts_negative))]
responses_df_negative = pd.DataFrame(responses_negative, columns=['text','response'])
responses_df_negative['labels'] = 0

0it [00:00, ?it/s]

In [308]:
pd.concat([responses_df_postive, responses_df_negative], axis=0, ignore_index=True).to_csv(f'annotations/synthetic/{clause_type}_synthetic_gpt4.csv')

# Train and evaluate classifier

In [347]:
import pandas as pd
from torch.utils.data import DataLoader
from pathlib import Path
import evaluate
from datasets import Dataset, DatasetDict
from transformers import AdamW
from tqdm.auto import tqdm
from transformers import get_scheduler
from torch.nn.functional import softmax
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from transformers import AutoTokenizer, DataCollatorWithPadding

In [309]:
# clause_type = 'opt-out' #'arbitration' | 'opt-out' | 'class_waiver'

In [310]:

# processed_data_dir = Path('processed_data/multigenre')
# metadata = pd.read_csv(processed_data_dir / 'metadata.tsv',sep='\t')

In [333]:
# # Load the data from CSV
# clause_type = 'arbitration'
# annotator = '_gpt4'
# df_annotations = pd.read_csv(f'annotations/gpt4_annotations/{clause_type}_annotations{annotator}.csv', index_col=0) 
# df_annotations

In [334]:
train.value_counts('labels')

labels
1    20
0     4
Name: count, dtype: int64

In [335]:
df_sample = metadata.sample(n=200).reset_index(drop=True)
sents = df_sample.sentence.to_list()
sents = [s for s in sents if s not in train.text.to_list()]
df_sample = pd.DataFrame(sents, columns=['text'])
df_sample['labels'] = 0
df_sample.shape

(200, 2)

In [348]:
train_data = pd.concat([train[['text','labels']], df_sample[['text','labels']] ], axis=0, ignore_index=True).reset_index(drop=True)

In [349]:
train_data

                                                  text  labels
0    this agreement requires final and binding arbi...       1
1    you agree that compliance with [company] is a ...       1
2    if we are unable to resolve a [company] within...       1
3    the laws of [company] , [company] , regardless...       0
4    informal dispute resolution you must try to in...       1
..                                                 ...     ...
219  you shall comply with all applicable federal l...       0
220  other players and users may , for example , se...       0
221  your program account may be cancelled if you d...       0
222  word / icon__chevron -- down.svg " \ * mergefo...       0
223  in such cases , we may raise or waive any lega...       0

[224 rows x 2 columns]

## Add synthetic data

In [350]:
syntethic_data = pd.read_csv(f'annotations/synthetic/{clause_type}_synthetic_gpt4.csv', index_col=0)

In [351]:
syntethic_data.rename(columns={'text':'prompt','response': 'text'}, inplace=True)

In [352]:
syntethic_data

,prompt,text,labels
0,\n \nYou are a helpful AI that create...,"by entering into this agreement, you and [comp...",1
1,\n \nYou are a helpful AI that create...,"by entering into this contract, you and [compa...",1
2,\n \nYou are a helpful AI that create...,any disputes or claims related to this agreeme...,1
3,\n \nYou are a helpful AI that create...,any controversy or claim arising out of or rel...,1
4,\n \nYou are a helpful AI that create...,any dispute or claim arising from or connected...,1
...,...,...,...
195,You are a helpful AI that creates synthetic d...,"in the event that any disagreement arises, the...",0
196,You are a helpful AI that creates synthetic d...,any disagreements that are not covered by [com...,0
197,You are a helpful AI that creates synthetic d...,participation in any [company] initiative requ...,0
198,You are a helpful AI that creates synthetic d...,the interpretation and enforcement of this agr...,0
199,You are a helpful AI that creates synthetic d...,the terms of this agreement shall be interpret...,0

In [353]:
 
train_data = pd.concat([train_data, syntethic_data[['text','labels']]], axis=0, ignore_index=True).reset_index(drop=True)

                                                 text  labels
83  for any action at law or in equity relating to...       0
80  these terms form an agreement between you and ...       1
76  dispute resolution through arbitration or smal...       1
98  if we are not able to resolve the [company] by...       1
36  [company] ( [company] ) will administer the ar...       1
..                                                ...     ...
97  agreement to arbitrate you and [company] agree...       1
79  you and [company] agree that such arbitration ...       1
44  dispute resolution , arbitration agreement , a...       1
61  [company] , whether arising out of or relating...       1
51  you and [company] agree to submit to the perso...       0

[72 rows x 2 columns]

## Train the model

In [363]:
checkpoint = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

def tokenize_function(example):
    return tokenizer(example["text"], truncation=True)



# Combine into a DatasetDict
dataset = DatasetDict({
    'train':  Dataset.from_pandas(train_data),
    'test': Dataset.from_pandas(test[['text','labels']].reset_index(drop=True)),
})

dataset

/Users/kasparbeelen/anaconda3/envs/tou/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

DatasetDict({
    train: Dataset({
        features: ['text', 'labels'],
        num_rows: 424
    })
    test: Dataset({
        features: ['text', 'labels'],
        num_rows: 72
    })
})

In [364]:
tokenized_datasets = dataset.map(tokenize_function, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

Map:   0%|          | 0/424 [00:00<?, ? examples/s]

Map:   0%|          | 0/72 [00:00<?, ? examples/s]

In [365]:
tokenized_datasets

DatasetDict({
    train: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 424
    })
    test: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 72
    })
})

In [366]:

tokenized_datasets = tokenized_datasets.remove_columns(["text"])
tokenized_datasets.set_format("torch")
tokenized_datasets["train"].column_names

['labels', 'input_ids', 'attention_mask']

In [367]:
tokenized_datasets

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 424
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'attention_mask'],
        num_rows: 72
    })
})

In [368]:
train_dataloader = DataLoader(
    tokenized_datasets["train"], shuffle=True, batch_size=8, collate_fn=data_collator
)
eval_dataloader = DataLoader(
    tokenized_datasets["test"], batch_size=8, collate_fn=data_collator
)

In [369]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)
model.to('mps')


optimizer = AdamW(model.parameters(), lr=1e-5) # eps=1e-6, weight_decay=0.2



num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)
print(num_training_steps)



progress_bar = tqdm(range(num_training_steps))
metric = evaluate.load("glue", "mrpc")

model.train()
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        loss = outputs.loss
        loss.backward()

        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)




    model.eval()
    for batch in eval_dataloader:
        batch = {k: v.to(device) for k, v in batch.items()}
        with torch.no_grad():
            outputs = model(**batch)

        logits = outputs.logits
        predictions = torch.argmax(logits, dim=-1)
        metric.add_batch(predictions=predictions, references=batch["labels"])

    print(metric.compute())

/Users/kasparbeelen/anaconda3/envs/tou/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

159

/Users/kasparbeelen/anaconda3/envs/tou/lib/python3.10/site-packages/transformers/optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

  0%|          | 0/159 [00:00<?, ?it/s]

{'accuracy': 0.16666666666666666, 'f1': 0.0}
{'accuracy': 0.8472222222222222, 'f1': 0.912}
{'accuracy': 0.8472222222222222, 'f1': 0.9090909090909091}

In [ ]:
model.save_pretrained(f"./models/{clause_type}_model")
tokenizer.save_pretrained(f"./models/{clause_type}_model")

# Apply Classifier

In [3]:
from torch.nn.functional import softmax
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from transformers import AutoTokenizer, DataCollatorWithPadding

In [16]:
processed_data_dir = Path('processed_data/multigenre')
file_name = processed_data_dir / 'metadata.tsv'
metadata = pd.read_csv(file_name,sep='\t')
metadata.fillna('', inplace=True)
print(len(metadata))

149261

In [27]:
clause_type = 'anti-scraping'
model = AutoModelForSequenceClassification.from_pretrained(f'models/{clause_type}_model')
tokenizer = AutoTokenizer.from_pretrained(f'models/{clause_type}_model')

In [28]:
metadata.head()

,file_name,platform,genre,tag,sentence,logits_arbitration,prob_1_arbitration,arbitration
0,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,privacy policy effective date : [mask] [mask] ...,"[[tensor(0.9787), tensor(0.0213)]]",0.021337,0.0
1,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,the data controller is [mask] [mask] and can b...,"[[tensor(0.9763), tensor(0.0237)]]",0.023692,0.0
2,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,the data protection officer is : [mask] [mask]...,"[[tensor(0.9772), tensor(0.0228)]]",0.022761,0.0
3,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,[mask] ec4 m 7ef sciplaydpo@scientificgames.co...,"[[tensor(0.9687), tensor(0.0313)]]",0.031294,0.0
4,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,you may also use the link found at the end of ...,"[[tensor(0.9769), tensor(0.0231)]]",0.023066,0.0

In [29]:
metadata.iloc[137375:137380]

,file_name,platform,genre,tag,sentence,logits_arbitration,prob_1_arbitration,arbitration
137375,tumblr_tos_social,tumblr,social,ToS,open source disclosures \n you can find disclo...,"[[tensor(0.9766), tensor(0.0234)]]",0.023355,0.0
137376,tumblr_tos_social,tumblr,social,ToS,,"[[tensor(0.7748), tensor(0.2252)]]",0.225161,0.0
137377,huggingface_tou_ai,huggingface,ai,ToS,thanks for using [mask] [mask] and being part ...,"[[tensor(0.9522), tensor(0.0478)]]",0.047831,0.0
137378,huggingface_tou_ai,huggingface,ai,ToS,we drafted the following [mask] [mask] [mask] ...,"[[tensor(0.9751), tensor(0.0249)]]",0.024918,0.0
137379,huggingface_tou_ai,huggingface,ai,ToS,we are very much open to feedback - contact us...,"[[tensor(0.9687), tensor(0.0313)]]",0.031342,0.0

In [30]:
tqdm.pandas()
metadata[f'logits_{clause_type}'] = metadata.progress_apply(lambda x: 
                    softmax(model(**tokenizer(x.sentence, return_tensors='pt', truncation=True)).logits.detach(), dim=1), 
                          axis=1)

  0%|          | 0/149261 [00:00<?, ?it/s]

100%|██████████| 149261/149261 [1:12:32<00:00, 34.29it/s]

In [31]:
metadata[f'prob_1_{clause_type}'] = metadata[f'logits_{clause_type}'].apply(lambda x: x[0][1].item())
metadata[clause_type] = .0
metadata.loc[metadata[f'prob_1_{clause_type}'] > .5, clause_type] = 1

In [32]:
metadata.drop(columns=['logits_arbitration', 'logits_anti-scraping'], inplace=True)

In [33]:
metadata.to_csv(processed_data_dir /f'{file_name.stem}_annotated.tsv', sep='\t', index=False)

In [34]:
metadata.head()

,file_name,platform,genre,tag,sentence,prob_1_arbitration,arbitration,prob_1_anti-scraping,anti-scraping
0,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,privacy policy effective date : [mask] [mask] ...,0.021337,0.0,0.014945,0.0
1,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,the data controller is [mask] [mask] and can b...,0.023692,0.0,0.021128,0.0
2,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,the data protection officer is : [mask] [mask]...,0.022761,0.0,0.016152,0.0
3,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,[mask] ec4 m 7ef sciplaydpo@scientificgames.co...,0.031294,0.0,0.028223,0.0
4,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,you may also use the link found at the end of ...,0.023066,0.0,0.019758,0.0

In [ ]:
#metadata.sort_values('prob_1', ascending=False).head(10)

In [ ]:
df_deduplicated = metadata.drop_duplicates(subset=['sentence'])
df_deduplicated['annotated'] = df_deduplicated.sentence.isin(df_annotations.text)
int_labels = [((0.95,1.0),'confident_positive'),( (0.80,.95), 'sure_positive'),((0.60,.80), 'leaning_positive'),
                   ((0.50,.60), 'borderline_positive'),((0.40,.50), 'borderline_negative'),
                   ((0.20,.40), 'leaning_negative'),((0.05,.20), 'sure_negative'),((0.0,.05), 'confident_negative')]
for interval, label in int_labels:


    df_deduplicated.loc[df_deduplicated.prob_1.between(*interval),'category']  = label

In [ ]:
pd.concat([df_deduplicated[df_deduplicated.category == label].sample(10)
    for _ , label in int_labels], axis=0)[['sentence','category']].to_csv(f'annotations/inference/{clause_type}_automatic_annotations_by_category.csv')

In [ ]:
metadata[metadata.prob_1 > .5].to_csv(f'annotations/inference/{clause_type}_inference.csv')

## Fin