In [1]:
from tools.utils import *
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import torch
import spacy

/Users/kasparbeelen/anaconda3/envs/tou/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

# Prepare data for annotation

In [2]:
# prepare the spacy model and pipeline
nlp = spacy.load("en_core_web_sm")
nlp.disable_pipes("tagger", "parser", "attribute_ruler", "lemmatizer")
nlp.add_pipe('sentencizer')

In [3]:
processed_data_dir = Path('processed_data')

In [5]:
metadata

        platform      year                                           sentence
0        Twitter  20150501  [mask] [mask] [mask] [mask] [mask] [mask] [mas...
1        Twitter  20150501  your access to and use of the services are con...
2        Twitter  20150501  by accessing or using the services you agree t...
3        Twitter  20150501  basic terms you are responsible for your use o...
4        Twitter  20150501  most content you submit , post , or display th...
...          ...       ...                                                ...
105240  LinkedIn  20200801        how to contact us our contact information .
105241  LinkedIn  20200801  our help center also provides information abou...
105242  LinkedIn  20200801  for general inquiries , you may contact us onl...
105243  LinkedIn  20200801  for legal notices or service of process , you ...
105244  LinkedIn  20200801                                      [mask] [mask]

[105245 rows x 3 columns]

In [4]:
embeddings = np.loadtxt(processed_data_dir / 'embedding.tsv')
metadata = pd.read_csv(processed_data_dir / 'metadata.tsv',sep='\t')
print(len(embeddings), len(metadata))

105245 105245

In [ ]:
clause_type = 'class_waiver' #'arbitration' | 'opt-out' | 'class_waiver' | 'anti-scraping'
examples_df = pd.read_excel(f'annotations/{clause_type}_clauses.xlsx', sheet_name='Sheet1')

In [ ]:
examples_df['processed_text'] = examples_df['Examples'].apply(lambda x: 'clustering: ' + replace_named_entities(nlp(x)))

In [ ]:
examples_df['processed_text']

In [ ]:
# next line is to check if MPS is available
device = 'mps' if torch.backends.mps.is_available() else 'cpu'
# comment next line if you are want to run code on a GPU
#device = 'cuda' if torch.cuda.is_available() else device

# load the nomic embed model
model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True) # trust_remote_code is needed to use the encode method
# send the model to the device
#model.to(device)
#print(device)

In [ ]:
target_embeddings = model.encode(examples_df['processed_text'].tolist())

In [ ]:
average_embedding = target_embeddings.mean(axis=0)

In [ ]:
similarity_scores = cosine_similarity(embeddings, [average_embedding])
top_n_position = np.argpartition(similarity_scores.reshape(-1), -500)[-500:][::-1]
out_csv = pd.DataFrame(metadata.iloc[top_n_position].sentence.unique())
out_csv.columns = ['sentence']
out_csv['label'] = 0
#out_csv['similarity'] = similarity_scores[top_n_position]
out_csv.to_csv(f'annotations/{clause_type}_most_similar_to_average.csv')

In [ ]:
similarity_scores = cosine_similarity(embeddings, target_embeddings)
similarity_scores = similarity_scores.max(axis=1)
top_n_position = np.argpartition(similarity_scores, -500)[-500:][::-1]
out_csv = pd.DataFrame(metadata.iloc[top_n_position].sentence.unique())
out_csv.columns = ['sentence']
out_csv['label'] = 0
#out_csv['similarity'] = similarity_scores[top_n_position]
out_csv.to_csv(f'annotations/{clause_type}_most_similar_to_individual.csv')

## Annotate selected examples with ChatGPT

In [ ]:
# prepare examples for annotation
df1 = pd.read_csv(f'annotations/{clause_type}_most_similar_to_individual.csv', index_col=0)
df2 = pd.read_csv(f'annotations/{clause_type}_most_similar_to_average.csv', index_col=0)
print(len(df1) + len(df2))
df = pd.concat([df1, df2], axis=0).drop_duplicates(subset='sentence')
print(df.shape)

In [ ]:
# prepare prompts for annotation
sentences = df.sentence.to_list()
prompts =["""Below are ten examples of {0} clauses.\n\n{1}\n\n Is the following sentence a {0} clause? Please select only yes or no.
 {2}""".format(
     clause_type,examples_df['Examples'].sample(10).str.cat(sep='\n'),s)  for s in sentences]
print(len(prompts),prompts[0])

In [ ]:
sentences = df.sentence.to_list()
syntethic_prompts =["""Below are ten examples of {0} clauses.\n\n{1}\n\nGenerate a new sentence similar but not identical to these examples and has the same function as {0} clause.
 """.format(
     clause_type,examples_df['Examples'].sample(10).str.cat(sep='\n'))  for _ in range(100)]
print(len(syntethic_prompts),syntethic_prompts[0])

In [ ]:
# Set up OpenAI API credentials
from openai import OpenAI
client = OpenAI()


def generate_response(prompt,model='gpt-4o-mini', max_tokens=100,temperature=.0):
    # Generate a response using OpenAI ChatGPT
    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_tokens,
        temperature=temperature,
        n=1,
        stop=None,
        timeout=10
    )

    # Extract the generated response from the API response
    #generated_response = response.choices[0].text.strip()

    return response.choices[0].message.content

In [ ]:
responses = [(sentences[i],generate_response(p,model='gpt-4o',max_tokens=2)) for i, p in tqdm(enumerate(prompts))]
responses_df = pd.DataFrame(responses, columns=['text','response'])

In [ ]:
responses_df['synthetic'] = 0

In [ ]:
responses_df.value_counts('response')

In [ ]:
responses_df.response.unique()

In [ ]:
syntethic_data = [generate_response(p,max_tokens=200,temperature=.3) for i, p in tqdm(enumerate(syntethic_prompts))]

In [ ]:
syntethic_data_df = pd.DataFrame(syntethic_data, columns=['text'])
syntethic_data_df['text'] = syntethic_data_df['text'].str.lower()
syntethic_data_df['labels'] = 1
syntethic_data_df['synthetic'] = 1
syntethic_data_df.iloc[1]

In [ ]:
responses_df.replace({'response': {'Yes.': 1,'Yes': 1, 'No': 0,'No.': 0}}, inplace=True)
responses_df.rename(columns={'response': 'labels'}, inplace=True)

In [ ]:
annotations_gpt = pd.concat([responses_df, syntethic_data_df], axis=0)

In [ ]:
annotations_gpt.to_csv(f'annotations/{clause_type}_annotations_gpt4.csv')
annotations_gpt.shape

In [ ]:
annotations_gpt

# Load annotations and train a classifier

In [ ]:
import pandas as pd
from torch.utils.data import DataLoader
from pathlib import Path
import evaluate
from datasets import Dataset
from transformers import AdamW
from tqdm.auto import tqdm
from transformers import get_scheduler
from torch.nn.functional import softmax
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from transformers import AutoTokenizer, DataCollatorWithPadding

In [ ]:

processed_data_dir = Path('processed_data')
metadata = pd.read_csv(processed_data_dir / 'metadata.tsv',sep='\t')

In [ ]:
# Load the data from CSV
clause_type = 'arbitration'
annotator = '_gpt4'
df_annotations = pd.read_csv(f'annotations/{clause_type}_annotations{annotator}.csv', index_col=0) 
df_annotations

In [ ]:
df_annotations.value_counts('labels')

In [ ]:
df_sample = metadata.sample(n=200).reset_index(drop=True)
sents = df_sample.sentence.to_list()
sents = [s for s in sents if s not in df_annotations.text.to_list()]
df_sample = pd.DataFrame(sents, columns=['text'])
df_sample['labels'] = 0
df_sample.shape

In [ ]:
data = pd.concat([df_annotations[['text','labels']], df_sample[['text','labels']] ], axis=0).reset_index(drop=True)

In [ ]:
data

In [ ]:
checkpoint = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

def tokenize_function(example):
    return tokenizer(example["text"], truncation=True)

dataset = Dataset.from_pandas(data)
tokenized_datasets = dataset.map(tokenize_function, batched=True)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [ ]:
tokenized_datasets

In [ ]:
tokenized_datasets = tokenized_datasets.train_test_split(test_size=0.2)
tokenized_datasets = tokenized_datasets.remove_columns(["text"])
tokenized_datasets.set_format("torch")
tokenized_datasets["train"].column_names

In [ ]:
tokenized_datasets

In [ ]:
train_dataloader = DataLoader(
    tokenized_datasets["train"], shuffle=True, batch_size=8, collate_fn=data_collator
)
eval_dataloader = DataLoader(
    tokenized_datasets["test"], batch_size=8, collate_fn=data_collator
)

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)
model.to('mps')


optimizer = AdamW(model.parameters(), lr=1e-5, eps=1e-6, weight_decay=0.2)



num_epochs = 5
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)
print(num_training_steps)



progress_bar = tqdm(range(num_training_steps))
metric = evaluate.load("glue", "mrpc")

model.train()
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        loss = outputs.loss
        loss.backward()

        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)




    model.eval()
    for batch in eval_dataloader:
        batch = {k: v.to(device) for k, v in batch.items()}
        with torch.no_grad():
            outputs = model(**batch)

        logits = outputs.logits
        predictions = torch.argmax(logits, dim=-1)
        metric.add_batch(predictions=predictions, references=batch["labels"])

    print(metric.compute())

In [ ]:
model.save_pretrained(f"./{clause_type}_model")
tokenizer.save_pretrained(f"./{clause_type}_model")

# Apply Classifier

In [3]:
from torch.nn.functional import softmax
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from transformers import AutoTokenizer, DataCollatorWithPadding

In [16]:
processed_data_dir = Path('processed_data')
file_name = processed_data_dir / 'metadata_genre.tsv'
metadata = pd.read_csv(file_name,sep='\t')
metadata.fillna('', inplace=True)
print(len(metadata))

149261

In [27]:
clause_type = 'anti-scraping'
model = AutoModelForSequenceClassification.from_pretrained(f'{clause_type}_model')
tokenizer = AutoTokenizer.from_pretrained(f'{clause_type}_model')

In [28]:
metadata.head()

,file_name,platform,genre,tag,sentence,logits_arbitration,prob_1_arbitration,arbitration
0,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,privacy policy effective date : [mask] [mask] ...,"[[tensor(0.9787), tensor(0.0213)]]",0.021337,0.0
1,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,the data controller is [mask] [mask] and can b...,"[[tensor(0.9763), tensor(0.0237)]]",0.023692,0.0
2,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,the data protection officer is : [mask] [mask]...,"[[tensor(0.9772), tensor(0.0228)]]",0.022761,0.0
3,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,[mask] ec4 m 7ef sciplaydpo@scientificgames.co...,"[[tensor(0.9687), tensor(0.0313)]]",0.031294,0.0
4,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,you may also use the link found at the end of ...,"[[tensor(0.9769), tensor(0.0231)]]",0.023066,0.0

In [29]:
metadata.iloc[137375:137380]

,file_name,platform,genre,tag,sentence,logits_arbitration,prob_1_arbitration,arbitration
137375,tumblr_tos_social,tumblr,social,ToS,open source disclosures \n you can find disclo...,"[[tensor(0.9766), tensor(0.0234)]]",0.023355,0.0
137376,tumblr_tos_social,tumblr,social,ToS,,"[[tensor(0.7748), tensor(0.2252)]]",0.225161,0.0
137377,huggingface_tou_ai,huggingface,ai,ToS,thanks for using [mask] [mask] and being part ...,"[[tensor(0.9522), tensor(0.0478)]]",0.047831,0.0
137378,huggingface_tou_ai,huggingface,ai,ToS,we drafted the following [mask] [mask] [mask] ...,"[[tensor(0.9751), tensor(0.0249)]]",0.024918,0.0
137379,huggingface_tou_ai,huggingface,ai,ToS,we are very much open to feedback - contact us...,"[[tensor(0.9687), tensor(0.0313)]]",0.031342,0.0

In [30]:
tqdm.pandas()
metadata[f'logits_{clause_type}'] = metadata.progress_apply(lambda x: 
                    softmax(model(**tokenizer(x.sentence, return_tensors='pt', truncation=True)).logits.detach(), dim=1), 
                          axis=1)

  0%|          | 0/149261 [00:00<?, ?it/s]

100%|██████████| 149261/149261 [1:12:32<00:00, 34.29it/s]

In [31]:
metadata[f'prob_1_{clause_type}'] = metadata[f'logits_{clause_type}'].apply(lambda x: x[0][1].item())
metadata[clause_type] = .0
metadata.loc[metadata[f'prob_1_{clause_type}'] > .5, clause_type] = 1

In [32]:
metadata.drop(columns=['logits_arbitration', 'logits_anti-scraping'], inplace=True)

In [33]:
metadata.to_csv(processed_data_dir /f'{file_name.stem}_annotated.tsv', sep='\t', index=False)

In [34]:
metadata.head()

,file_name,platform,genre,tag,sentence,prob_1_arbitration,arbitration,prob_1_anti-scraping,anti-scraping
0,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,privacy policy effective date : [mask] [mask] ...,0.021337,0.0,0.014945,0.0
1,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,the data controller is [mask] [mask] and can b...,0.023692,0.0,0.021128,0.0
2,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,the data protection officer is : [mask] [mask]...,0.022761,0.0,0.016152,0.0
3,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,[mask] ec4 m 7ef sciplaydpo@scientificgames.co...,0.031294,0.0,0.028223,0.0
4,JackpotPartyCasinoSlotsPP_gaming,JackpotPartyCasinoSlotsPP,gaming,PP,you may also use the link found at the end of ...,0.023066,0.0,0.019758,0.0

In [ ]:
#metadata.sort_values('prob_1', ascending=False).head(10)

In [ ]:
df_deduplicated = metadata.drop_duplicates(subset=['sentence'])
df_deduplicated['annotated'] = df_deduplicated.sentence.isin(df_annotations.text)
int_labels = [((0.95,1.0),'confident_positive'),( (0.80,.95), 'sure_positive'),((0.60,.80), 'leaning_positive'),
                   ((0.50,.60), 'borderline_positive'),((0.40,.50), 'borderline_negative'),
                   ((0.20,.40), 'leaning_negative'),((0.05,.20), 'sure_negative'),((0.0,.05), 'confident_negative')]
for interval, label in int_labels:


    df_deduplicated.loc[df_deduplicated.prob_1.between(*interval),'category']  = label

In [ ]:
pd.concat([df_deduplicated[df_deduplicated.category == label].sample(10)
    for _ , label in int_labels], axis=0)[['sentence','category']].to_csv(f'annotations/{clause_type}_automatic_annotations_by_category.csv')

In [ ]:
metadata[metadata.prob_1 > .5].to_csv(f'annotations/{clause_type}_inference.csv')

## Fin